---
title: "Data Aquisation for 'Plenarprotokolle'"
author: "Marlon Schumacher"
date: "03.06.2019"
output: pdf_document
---

This `.rmd` file contains the code for the data aquisation process for the *Plenarprotokolle* of the German Bundestag.


## package import
```{r}
# install.packages("pacman")
pacman::p_load(pdftools, dplyr, ggplot2, stringr, tidyr, purrr, lubridate, magrittr, tm, haven, readr, XML, methods)
```

## getting filenames for each legislature
```{r}
filenames_pp14 <- list.files("/Users/marlonschumacher/Documents/2_Master/4. Fachsemester/master_thesis/Plenarprotokolle/pp14_1998_2002")
filenames_pp15 <- list.files("/Users/marlonschumacher/Documents/2_Master/4. Fachsemester/master_thesis/Plenarprotokolle/pp15_2002_2005")
filnemaes_pp16 <- list.files("/Users/marlonschumacher/Documents/2_Master/4. Fachsemester/master_thesis/Plenarprotokolle/pp16_2005_2009")
filenames_pp17 <- list.files("/Users/marlonschumacher/Documents/2_Master/4. Fachsemester/master_thesis/Plenarprotokolle/pp17_2009_2013")
filenames_pp18 <- list.files("/Users/marlonschumacher/Documents/2_Master/4. Fachsemester/master_thesis/Plenarprotokolle/pp18_2013_2017")
```

## creating main function
```{r}
pp14_03 <- XML::xmlToList("/Users/marlonschumacher/Documents/2_Master/4. Fachsemester/master_thesis/Plenarprotokolle/pp14_1998_2002/14003.xml")
                          
# without replacement
str_split(pp14_03$TEXT, "\n")

# with replacement
str_replace_all(pp14_03$TEXT, "-\n", "") %>%
  str_split(., "\n")
```

```{r}
#bt18098_list

bt18098_list[[1]]
```


```{r}
# Dokumentenart
bt18098_list[[2]]

# NR
bt18098_list[[3]]

# Datum
bt18098_list[[4]]

# Titel
bt18098_list[[5]]

# Text
text_bt18098 <- bt18098_list[[6]]
```

```{r}
df_csv <- read.csv("datensatz_masterthesis.csv", header = TRUE, sep = ";", stringsAsFactors = F, encoding = "UTF-8")

Encoding(df_csv$content) <- "UTF-8"
Encoding(df_csv$content)

replacement_enc <- function(var){
  var <- gsub("\xe4", "ä", var)
}

replacement_enc(df_csv$content)
df_csv$content
```

## OLD CODE
```{r}
#prot1 <- pdftools::pdf_text("19084_prot.pdf")

read <- readPDF(control = list(text = "-layout"))
document <- Corpus(URISource("19084_prot.pdf"), readerControl = list(reader = read))
doc <- content(document[[1]])

doc %>% 
  str_split(., "\n")
```
